import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0).replace(/\u00a0/g,' ');
const num=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n)||0);
const pct=n=>`${(Number(n)||0).toLocaleString('id-ID',{maximumFractionDigits:1})}%`;

function App(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[year,setYear]=useState(2026),[years,setYears]=useState([2026]),[tab,setTab]=useState('dashboard'),[activeKpi,setActiveKpi]=useState(null),[pulse,setPulse]=useState(0);
  const load=async()=>{try{setLoading(true);const r=await fetch(`/api/public/dashboard?year=${year}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||`HTTP ${r.status}`);setData(j);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{(async()=>{try{const r=await fetch('/api/public/years',{cache:'no-store'});const j=await r.json();if(j.ok&&j.years?.length){setYears(j.years);if(!j.years.includes(year))setYear(j.years[0]);}}catch{}})();load();const t=setInterval(()=>load(),3000);const p=setInterval(()=>setPulse(v=>v+1),1800);return()=>{clearInterval(t);clearInterval(p)}},[year]);
  const k=data?.kpi||{};
  const cards=useMemo(()=>[
    {id:'budget',label:'Total Anggaran',value:money(k.totalAnggaran),note:'Berdasarkan anggaran resmi pada Realisasi Fisik & Keu',icon:'Rp'},
    {id:'financial',label:'Realisasi Keuangan',value:money(k.realisasiKeuangan),note:'Akumulasi realisasi keuangan',icon:'↗'},
    {id:'serapan',label:'Serapan Keuangan',value:pct(k.serapan),note:'Realisasi Keuangan ÷ Anggaran × 100',icon:'%'},
    {id:'physical',label:'Realisasi Fisik',value:pct(k.realisasiFisik),note:'Nilai fisik resmi/tertimbang dari sumber',icon:'◌'},
    {id:'pkpt',label:'Penugasan PKPT',value:num(k.penugasan),note:`${num(k.selesai)} selesai • ${num(k.berjalan)} berjalan • ${num(k.belum)} belum`,icon:'◎'},
    {id:'output',label:'Total Output',value:num((k.outputUtama||0)+(k.outputPenunjang||0)),note:`Utama ${num(k.outputUtama)} • Penunjang ${num(k.outputPenunjang)}`,icon:'▦'}
  ],[k]);
  const sourceTitle=tab==='dashboard'?'Pusat Kendali Realisasi Kinerja':tab==='realisasi'?'Realisasi Fisik & Keuangan':tab==='kinerja'?'Kinerja & Monitoring':'Penugasan & Output';
  return <div className="app">
    <header className="top"><div className="brand"><div className="brand-mark">ID</div><div><b>INSPEKTORAT DAERAH KABUPATEN MAHAKAM ULU</b><span>PUBLIC PERFORMANCE DASHBOARD</span></div></div><div className="top-right"><span className="live"><i/> LIVE DATA</span><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y}>{y}</option>)}</select></div></header>
    <div className="shell"><aside className="side"><div className="side-title">MONITORING PUBLIK</div>{[['dashboard','✦','Dashboard'],['realisasi','◒','Realisasi'],['kinerja','◫','Kinerja'],['penugasan','◎','Penugasan']].map(([id,ic,t])=><button key={id} className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)}><span>{ic}</span>{t}</button>)}<div className="side-foot"><small>SUMBER</small><b>Google Sheets</b><span>melalui Cloudflare Backend</span><small className="sync">Sinkron otomatis ±3 detik</small></div></aside>
      <main className="main"><div className="ambient a1"/><div className="ambient a2"/><section className="hero"><div><span className="eyebrow">INSPEKTORAT DAERAH KABUPATEN MAHAKAM ULU • TA {year}</span><h1>{sourceTitle.split(' ')[0]} <em>{sourceTitle.split(' ').slice(1).join(' ')}</em></h1><p>Dashboard publik untuk membaca capaian, serapan anggaran, realisasi fisik, penugasan, output, serta perkembangan kinerja dari database pusat.</p><div className="hero-badges"><span>● Backend aktif</span><span>● Data terhubung</span><span>● Read-only publik</span></div></div><div className={`orb p${pulse%4}`}><div className="ring r1"/><div className="ring r2"/><div className="core">ID</div><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/></div></section>
      {loading&&!data?<div className="loading panel"><div className="loader"/><span>Mengambil data KPI dari database pusat…</span></div>:error&&!data?<div className="error panel"><b>Backend belum terhubung</b><span>{error}</span><button onClick={load}>Coba lagi</button></div>:<>
        {tab==='dashboard'&&<Dashboard cards={cards} k={k} data={data} onKpi={setActiveKpi}/>} 
        {tab==='realisasi'&&<Realisasi k={k} onKpi={setActiveKpi}/>} 
        {tab==='kinerja'&&<Kinerja k={k} data={data}/>} 
        {tab==='penugasan'&&<Penugasan k={k}/>} 
      </>}
      <footer>Data ditampilkan dari database pusat melalui backend Cloudflare. Dashboard publik tidak menyediakan fungsi edit atau import.</footer>
      </main></div>{activeKpi&&<KpiModal kpi={activeKpi} k={k} onClose={()=>setActiveKpi(null)}/>}</div>
}
function Dashboard({cards,k,data,onKpi}){return <>
  <div className="kpis">{cards.map(c=><button className="kpi" key={c.id} onClick={()=>onKpi(c)}><div className="kpi-top"><span>{c.icon}</span><small>DETAIL ↗</small></div><label>{c.label}</label><strong>{c.value}</strong><p>{c.note}</p></button>)}</div>
  <div className="grid3"><section className="panel gauge-panel"><div className="panel-title"><span>REALISASI</span><b>Serapan Keuangan</b></div><div className="gauge" style={{'--p':`${Math.min(100,Number(k.serapan)||0)}%`}}><div><strong>{pct(k.serapan)}</strong><small>SERAPAN</small></div></div><div className="stats"><div><small>ANGGARAN</small><b>{money(k.totalAnggaran)}</b></div><div><small>REALISASI</small><b>{money(k.realisasiKeuangan)}</b></div><div><small>SISA DANA</small><b>{money(k.sisaDana)}</b></div></div></section>
  <section className="panel"><div className="panel-title"><span>FISIK</span><b>Profil Capaian</b></div><div className="bars">{[['Strategis',k.capaian?.strategic],['Program',k.capaian?.program],['Kegiatan',k.capaian?.kegiatanUtama],['Penunjang',k.capaian?.kegiatanPenunjang],['SUB U',k.capaian?.subUtama],['SUB P',k.capaian?.subPenunjang],['Renaksi',k.capaian?.renaksi],['Monev',k.capaian?.monevProgram]].map(([n,v])=><div className="bar" key={n}><span style={{height:`${Math.max(5,Math.min(100,v||0))}%`}}/><small>{n}</small></div>)}</div></section>
  <section className="panel"><div className="panel-title"><span>PKPT</span><b>Progress Penugasan</b></div><div className="stack"><i style={{width:`${ratio(k.selesai,k.penugasan)}%`}}/><i style={{width:`${ratio(k.berjalan,k.penugasan)}%`}}/><i style={{width:`${ratio(k.belum,k.penugasan)}%`}}/></div><div className="legend"><span><i/>Selesai <b>{num(k.selesai)}</b></span><span><i/>Berjalan <b>{num(k.berjalan)}</b></span><span><i/>Belum <b>{num(k.belum)}</b></span></div><div className="output"><div><small>OUTPUT UTAMA</small><b>{num(k.outputUtama)}</b></div><div><small>OUTPUT PENUNJANG</small><b>{num(k.outputPenunjang)}</b></div></div></section></div>
  <section className="panel coverage"><div className="panel-title"><span>CAKUPAN DATA</span><b>Kelengkapan 14 Kertas Kerja</b><small>{pct(data.overallCompleteness)} rata-rata</small></div><div className="coverage-grid">{(data.sheets||[]).map(s=><div key={s.name}><div><b>{s.name}</b><span>{pct(s.percent)}</span></div><div className="track"><i style={{width:`${s.percent}%`}}/></div></div>)}</div></section>
</>}
function ratio(a,b){return b?Math.max(0,Math.min(100,(a/b)*100)):0}
function Realisasi({k,onKpi}){const rows=[['Total Anggaran',money(k.totalAnggaran)],['Realisasi Keuangan',money(k.realisasiKeuangan)],['Sisa Dana',money(k.sisaDana)],['Serapan',pct(k.serapan)],['Realisasi Fisik',pct(k.realisasiFisik)]];return <section><div className="section-title"><span>ANALITIK REALISASI</span><h2>Fisik & Keuangan</h2><p>Angka keuangan dan fisik dipisahkan agar tidak terjadi pencampuran basis perhitungan.</p></div><div className="metric-list">{rows.map(([a,b])=><button key={a} onClick={()=>onKpi({label:a,value:b,note:'Detail dari database pusat'})}><span>{a}</span><strong>{b}</strong><em>↗</em></button>)}</div><div className="panel formula"><span>LOGIKA PERHITUNGAN</span><b>Serapan Keuangan = Realisasi Keuangan ÷ Anggaran × 100</b><b>Realisasi Fisik = nilai fisik resmi/tertimbang dari sumber</b><b>Sisa Dana = Anggaran − Realisasi Keuangan</b></div></section>}
function Kinerja({k,data}){const items=[['Sasaran Strategis',k.capaian?.strategic],['Sasaran Program',k.capaian?.program],['Kegiatan Utama',k.capaian?.kegiatanUtama],['Kegiatan Penunjang',k.capaian?.kegiatanPenunjang],['SUBKegiatan Utama',k.capaian?.subUtama],['SUBKegiatan Penunjang',k.capaian?.subPenunjang],['Monev Renaksi IKU',k.capaian?.renaksi],['Monev Program',k.capaian?.monevProgram]];return <section><div className="section-title"><span>MONITORING</span><h2>Kinerja & Evaluasi</h2><p>Ringkasan capaian dihitung dari indikator target/realisasi pada masing-masing sumber.</p></div><div className="performance-grid">{items.map(([n,v])=><div className="perf panel" key={n}><div><b>{n}</b><strong>{pct(v)}</strong></div><div className="track"><i style={{width:`${Math.min(100,v||0)}%`}}/></div></div>)}</div></section>}
function Penugasan({k}){return <section><div className="section-title"><span>PKPT</span><h2>Progress Penugasan</h2><p>Ringkasan status penugasan yang teridentifikasi dalam sumber PKPT.</p></div><div className="pen-grid"><div className="big-num panel"><strong>{num(k.penugasan)}</strong><span>Total penugasan</span></div>{[['Selesai',k.selesai],['Berjalan',k.berjalan],['Belum',k.belum]].map(([n,v])=><div className="status panel" key={n}><small>{n}</small><strong>{num(v)}</strong><span>{pct(ratio(v,k.penugasan))} dari total</span></div>)}</div><div className="panel output-grid"><div><small>OUTPUT UTAMA</small><strong>{num(k.outputUtama)}</strong></div><div><small>OUTPUT PENUNJANG</small><strong>{num(k.outputPenunjang)}</strong></div><div><small>TOTAL OUTPUT</small><strong>{num((k.outputUtama||0)+(k.outputPenunjang||0))}</strong></div></div></section>}
function KpiModal({kpi,k,onClose}){return <div className="modal-back" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className="eyebrow">DETAIL KPI • TA</span><h2>{kpi.label}</h2><div className="modal-number">{kpi.value}</div><p>{kpi.note}</p><div className="modal-grid"><div><small>ANGGARAN</small><b>{money(k.totalAnggaran)}</b></div><div><small>REALISASI</small><b>{money(k.realisasiKeuangan)}</b></div><div><small>FISIK</small><b>{pct(k.realisasiFisik)}</b></div><div><small>PKPT</small><b>{num(k.penugasan)}</b></div></div><div className="formula-box"><small>SUMBER</small><b>Google Sheets • diproses di backend Cloudflare</b><span>Data publik bersifat read-only.</span></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
