import { getCookie, json, verifySession } from '../../lib/security.js';
import { getDriveFileModifiedTime } from '../../lib/google.js';

export async function onRequestGet({ request, env }) {
  if (!(await verifySession(env, getCookie(request, '__Host-kk_session')))) {
    return json({ ok: false, message: 'Unauthorized' }, 401);
  }

  // Prefer Google Drive file metadata: this changes when the central spreadsheet
  // is edited directly in Google Sheets, so the editor can refresh automatically.
  try {
    const meta = await getDriveFileModifiedTime(env);
    return json({
      ok: true,
      revision: `${meta.modifiedTime || '0'}:${meta.version || '0'}`,
      modifiedTime: meta.modifiedTime,
      version: meta.version,
      source: 'google-drive-metadata'
    });
  } catch {}

  // If Drive metadata is unavailable, use D1 revision markers generated by
  // Web 2 writes. This keeps realtime-after-save available without Drive.
  try {
    if (env.DB) {
      const row = await env.DB.prepare(
        `SELECT revision, updated_at FROM revision_state WHERE id='global'`
      ).first();
      return json({
        ok: true,
        revision: String(Number(row?.revision || 0)),
        updatedAt: row?.updated_at || null,
        source: 'd1'
      });
    }
  } catch {}

  return json({ ok: true, revision: null, source: 'unavailable', polling: false }, 200);
}
